#
# Default configuration will point to hungryman.perfect300rock.com/api/
# Change this to reflect the URL of your APIs.
#

hungryman:
  search:
    service:
      url:  http://hungryman.perfect300rock.com/api/search
  availability:
    service:
      url:  http://hungryman.perfect300rock.com/api/availability
  loadTest:
    searchesToCreate: 500
    
reactive:
  feign:
    client:
      config:
        default:
          options: 
            readTimeoutMillis: 60000
            writeTimeoutMillis: 60000
            responseTimeoutMillis: 60000